/* SEÇÃO 7: MAIS ALGUNS COMANDOS BÁSICOS */
/* FILTRANDO VALORES NULOS */
SELECT nome, sexo, endereco
FROM cliente
WHERE email IS NULL; -- NÃO SE USA IGUALDADE ANTES DA PALAVRA NULL (email = NULL)

SELECT nome, sexo, endereco
FROM cliente
WHERE email IS NOT NULL;

-- MUITA ATENÇÃO AO USA ELES COM JOIN
/* A CLÁUSULA UPDATE */
UPDATE cliente
SET email = 'LILIAN@HOTMAIL.COM';

/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA PRA VIDA INTEIRA */

UPDATE cliente
SET email = 'JOAO@IG.COM.BR'
WHERE nome = 'JOAO';

/* A CLÁUSULA DELETE */
/* NOTA: ANTES DE EXECUTAR UM DELETE, EXECUTE UM SELECT PARA CONFERIR OS DADOS QUE SERÃO DELETADOS
NUNCA SE ESQUEÇA DE USAR O WHERE PARA FILTRAR OS REGISTROS QUE DEVEM SER DELETADOS
FAÇA UM COUNT PARA TER MAIS CERTEZA AINDA DE QUE A QUANTIDADE DE REGISTROS DELETADOS ESTÁ CORRETA */

SELECT *
FROM cliente
WHERE nome = 'ANA';

SELECT COUNT(*)
FROM cliente
WHERE nome = 'ANA';

DELETE
FROM cliente
WHERE nome = 'ANA';

DELETE
FROM cliente
WHERE nome = 'CARLA' AND email = 'CARLA@TERATI.COM.BR';

/* LEMBRE-SE: AO USAR AS CLÁUSULAS LÓGICAS PARA FILTRAR OS DELETES, O OR TRAZ TODOS OS REGISTROS ONDE UMA DAS CONDIÇÕES É VERDADEIRA E O AND APENAS QUANDO TODAS AS CONDIÇÕES SÃO VERDADEIRAS */